debug: true
server:
  port: 8081
persistence-unit:
  name: persistence_unit
  description: Planet Scale
  provider: org.hibernate.jpa.HibernatePersistenceProvider
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://aws.connect.psdb.cloud:3306/hephaestus_foundary
  username: gwbx0c8j53988cx3uyiw
  password: pscale_pw_onUzFvXL7CkUClHVdBPWUI2Z2QJIiBF4AAJttvc21IY


#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://aws.connect.psdb.cloud:3306/hephaestus_foundary
#    username: gwbx0c8j53988cx3uyiw
#    password: pscale_pw_onUzFvXL7CkUClHVdBPWUI2Z2QJIiBF4AAJttvc21IY
#    hikari:
#      keepalive-time: 30000
#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQLDialect

